import pytest
from unittest.mock import Mock, patch, MagicMock
from google.genai.errors import APIError
import os

from src.core.config import ConfigManager
from src.modules.image_gen.gemini_adapter import GeminiImageAdapter
from src.modules.image_gen.schemas import ImageGenInput, ImageGenOutput
from src.modules.image_gen.exceptions import ImageGenerationError

@pytest.fixture
def mock_config_manager():
    config = Mock(spec=ConfigManager)
    config.get_api_key.return_value = "test_api_key"
    config.get_image_model.return_value = "imagen-3.0-generate-002"
    return config

def test_adapter_initialization(mock_config_manager):
    with patch('src.modules.image_gen.gemini_adapter.genai.Client') as mock_client:
        adapter = GeminiImageAdapter(mock_config_manager)
        assert adapter.api_key == "test_api_key"
        assert adapter.model_name == "imagen-3.0-generate-002"
        mock_client.assert_called_once_with(api_key="test_api_key")

def test_generate_success(mock_config_manager, tmp_path):
    with patch('src.modules.image_gen.gemini_adapter.genai.Client') as mock_client_class, \
         patch('src.modules.image_gen.gemini_adapter.Image.open') as mock_image_open, \
         patch('src.modules.image_gen.gemini_adapter.uuid.uuid4') as mock_uuid:
         
        mock_client_instance = Mock()
        mock_client_class.return_value = mock_client_instance
        
        # Mock the generation response
        mock_image = MagicMock()
        mock_image.image.image_bytes = b"fake_image_bytes"
        mock_response = MagicMock()
        mock_response.generated_images = [mock_image]
        mock_client_instance.models.generate_images.return_value = mock_response
        
        # Mock UUID
        mock_uuid.return_value = "1234-5678"
        
        adapter = GeminiImageAdapter(mock_config_manager)
        test_output_dir = str(tmp_path / "images")
        adapter.output_dir = test_output_dir
        
        input_data = ImageGenInput(prompt="An epic fantasy hero")
        output = adapter.generate(input_data)
        
        call_kwargs = mock_client_instance.models.generate_images.call_args.kwargs
        assert call_kwargs['model'] == "imagen-3.0-generate-002"
        assert call_kwargs['prompt'] == "An epic fantasy hero"
        assert call_kwargs['config'].aspect_ratio == "1:1"
        assert "ALLOW_ADULT" in str(call_kwargs['config'].person_generation).upper()
        
        assert isinstance(output, ImageGenOutput)
        assert output.image_path.endswith("1234-5678.png")

def test_generate_api_error(mock_config_manager):
    with patch('src.modules.image_gen.gemini_adapter.genai.Client') as mock_client_class:
        mock_client_instance = Mock()
        mock_client_instance.models.generate_images.side_effect = Exception("Test API error")
        mock_client_class.return_value = mock_client_instance
        
        adapter = GeminiImageAdapter(mock_config_manager)
        input_data = ImageGenInput(prompt="An epic fantasy hero")
        
        with pytest.raises(ImageGenerationError, match="Unexpected error during image generation"):
            adapter.generate(input_data)

def test_generate_save_success(mock_config_manager, tmp_path):
    with patch('src.modules.image_gen.gemini_adapter.genai.Client') as mock_client_class, \
         patch('src.modules.image_gen.gemini_adapter.Image.open') as mock_image_open, \
         patch('src.modules.image_gen.gemini_adapter.uuid.uuid4') as mock_uuid, \
         patch('src.modules.image_gen.gemini_adapter.os.makedirs') as mock_makedirs:
        
        mock_client_instance = Mock()
        mock_client_class.return_value = mock_client_instance
        
        # Mock the generation response
        mock_image = MagicMock()
        mock_image.image.image_bytes = b"fake_image_bytes"
        mock_response = MagicMock()
        mock_response.generated_images = [mock_image]
        mock_client_instance.models.generate_images.return_value = mock_response
        
        # Mock PIL Image.open
        mock_pil_image = MagicMock()
        mock_image_open.return_value = mock_pil_image
        
        # Mock UUID for predictable filename
        mock_uuid.return_value = "1234-5678"
        
        adapter = GeminiImageAdapter(mock_config_manager)
        # Override output_dir for testing
        test_output_dir = str(tmp_path / "images")
        adapter.output_dir = test_output_dir
        
        input_data = ImageGenInput(prompt="A test image")
        output = adapter.generate(input_data)
        
        # Verify Image generated by Gemini is processed twice (once for verify, once for save)
        assert mock_image_open.call_count == 2
        # Verify it tries to save the file
        expected_path = os.path.join(test_output_dir, "1234-5678.png")
        
        mock_pil_image.save.assert_called_once()
        saved_path = mock_pil_image.save.call_args[0][0]
        assert saved_path == expected_path
        
        # also check that makedirs was called with the right directory
        mock_makedirs.assert_called_once_with(test_output_dir, exist_ok=True)
        
        assert isinstance(output, ImageGenOutput)
        assert output.image_path == expected_path
