import os
import io
import uuid
from PIL import Image

from google import genai
from google.genai import types
from google.genai.errors import APIError, ClientError

from src.core.config import ConfigManager
from src.modules.image_gen.interface import BaseImageGenerator
from src.modules.image_gen.schemas import ImageGenInput, ImageGenOutput
from src.modules.image_gen.exceptions import ImageGenerationError

class GeminiImageAdapter(BaseImageGenerator):
    """Adapter for generating images using Google GenAI SDK's Imagen models."""

    def __init__(self, config_manager: ConfigManager):
        """Initialize the adapter with a configured client."""
        self.api_key = config_manager.get_api_key()
        self.model_name = config_manager.get_image_model() or "imagen-4.0-generate-001"
        self.client = genai.Client(api_key=self.api_key)

    def generate(self, input_data: ImageGenInput) -> ImageGenOutput:
        """
        Generate an image using the Gemini API.
        This simply returns the first iteration stub, proper image byte processing will be added next.
        """
        config = types.GenerateImagesConfig(
            number_of_images=1,
            aspect_ratio="1:1",
            output_mime_type="image/png",
            person_generation="allow_adult"
        )
        
        try:
            response = self.client.models.generate_images(
                model=self.model_name,
                prompt=input_data.prompt,
                config=config
            )
            
            if not response.generated_images:
                raise ImageGenerationError("No images were generated by the API.")
                
            image_bytes = response.generated_images[0].image.image_bytes
            
            try:
                # Validate integrity
                img_io = io.BytesIO(image_bytes)
                image = Image.open(img_io)
                image.verify()
                
                # Reopen to save
                img_io.seek(0)
                image = Image.open(img_io)
            except Exception as e:
                raise ImageGenerationError(f"Failed to process and validate image data: {e}")
                
            # Generate unique path and save
            output_dir = getattr(self, 'output_dir', os.path.join(os.getcwd(), 'output', 'images'))
            os.makedirs(output_dir, exist_ok=True)
            
            filename = f"{uuid.uuid4()}.png"
            filepath = os.path.join(output_dir, filename)
            
            image.save(filepath, format="PNG")
            
            return ImageGenOutput(image_path=filepath)
            
        except (APIError, ClientError) as e:
            raise ImageGenerationError(f"API Error during image generation: {e}")
        except Exception as e:
            raise ImageGenerationError(f"Unexpected error during image generation: {e}")